export enum AuthLogEvent {
	// FLOW
	SUBMIT_START = 'AUTH_SUBMIT_START',

	// REQUEST
	LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST',

	// VALIDATION
	INVALID_EMAIL = 'AUTH_INVALID_EMAIL',
	INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',

	// ERRORS
	NETWORK_ERROR = 'AUTH_NETWORK_ERROR',
	UNKNOWN_ERROR = 'AUTH_UNKNOWN_ERROR',
}
