version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL_DOCKER}
        VITE_APP_MODE: ${VITE_APP_MODE}
        VITE_AUTH_PROVIDER: ${VITE_AUTH_PROVIDER}
    container_name: sistema_gestion_frontend
    restart: unless-stopped
    ports:
      - '3001:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
